import { marked } from "marked";
import { Link } from "react-router-dom";
import AssignmentRoster from "./AssignmentRoster";
import { Badge } from "./ui/Badge";
import { Button } from "./ui/Button";
import { Card, CardContent, CardHeader, CardTitle } from "./ui/Card";
import { Icon } from "./ui/Icons";
import { formatDateTime } from "../lib/format";
import type { Assignment, AssignmentGroup } from "../types";

type Props = { assignment: Assignment; groups: AssignmentGroup[]; groupsLoading: boolean; pdfBriefUrl: string | null; submissionCount: number; reviewedCount: number; publicLinkCopied: boolean; copiedGroupId: string | null; manageOpen: boolean; onCopyPublicLink: () => void; onCopyGroupLink: (id: string) => void; onToggleManage: () => void };

export function GroupProjectWorkspace({ assignment, groups, groupsLoading, pdfBriefUrl, submissionCount, reviewedCount, publicLinkCopied, copiedGroupId, manageOpen, onCopyPublicLink, onCopyGroupLink, onToggleManage }: Props) {
  const closed = new Date(assignment.closesAt) <= new Date();
  const documentUrl = `/v2/api/assignments/${assignment.id}/brief`;
  const brief = assignment.sourceType === "pdf" ? (
    pdfBriefUrl ? <iframe src={pdfBriefUrl} className="h-[72vh] min-h-[560px] w-full border-0" title="Project brief" /> : <div className="flex h-[560px] items-center justify-center text-sm text-[var(--fg-muted)]">Loading document...</div>
  ) : assignment.sourceType === "docx" ? (
    <div className="flex min-h-[560px] flex-col items-center justify-center gap-3 px-6 text-center"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-[var(--accent-soft)] text-[var(--accent)]"><Icon.FileText className="h-6 w-6" /></div><div><p className="font-medium">DOCX project brief</p><p className="mt-1 text-sm text-[var(--fg-muted)]">Open or download the document to view the complete brief.</p></div><a href={documentUrl} target="_blank" rel="noreferrer"><Button size="sm"><Icon.Download className="h-3.5 w-3.5" /> Download DOCX</Button></a></div>
  ) : assignment.sourceMarkdown ? <div className="mdcontent min-h-[560px] text-sm leading-relaxed" dangerouslySetInnerHTML={{ __html: marked(assignment.sourceMarkdown) as string }} /> : assignment.sourceUrl ? (
    <div className="flex min-h-[560px] flex-col items-center justify-center gap-3 px-6 text-center"><Icon.External className="h-7 w-7 text-[var(--accent)]" /><p className="text-sm text-[var(--fg-muted)]">This project brief is hosted externally.</p><a href={assignment.sourceUrl} target="_blank" rel="noreferrer"><Button size="sm">Open project brief <Icon.External className="h-3.5 w-3.5" /></Button></a></div>
  ) : <div className="flex min-h-[560px] items-center justify-center text-sm text-[var(--fg-muted)]">No brief has been added yet.</div>;

  return <div className="flex flex-col gap-5">
    <div className="border-b border-[var(--border)] pb-5"><Link to="/teacher/group-projects" className="inline-flex items-center gap-1 text-xs font-medium text-[var(--fg-muted)] hover:text-[var(--accent)]"><Icon.ChevronLeft className="h-3 w-3" /> Group projects</Link><div className="mt-3 flex flex-wrap items-start justify-between gap-4"><div><div className="mb-1 flex items-center gap-2 text-xs font-medium uppercase tracking-wider text-[var(--fg-muted)]"><Icon.Users className="h-3.5 w-3.5" /> Group project</div><h1 className="text-2xl font-semibold tracking-tight">{assignment.title}</h1>{assignment.description && <p className="mt-1 max-w-2xl text-sm text-[var(--fg-muted)]">{assignment.description}</p>}</div><div className="flex flex-wrap gap-2"><Button variant="secondary" size="sm" onClick={onCopyPublicLink}><Icon.Link className="h-3.5 w-3.5" /> {publicLinkCopied ? "Project link copied" : "Copy public project link"}</Button><Button variant="secondary" size="sm" onClick={onToggleManage}><Icon.MoreHorizontal className="h-3.5 w-3.5" /> Manage project</Button></div></div>{manageOpen && <div className="mt-4 flex flex-wrap items-center gap-2 rounded-lg border border-[var(--border)] bg-[var(--surface-muted)]/40 p-3"><span className="mr-1 text-xs text-[var(--fg-muted)]">Project controls</span><Link to={`/teacher/assignments/${assignment.id}/edit`}><Button variant="secondary" size="sm"><Icon.Edit className="h-3.5 w-3.5" /> Edit details</Button></Link><Link to={`/teacher/assignments/${assignment.id}/groups`}><Button variant="secondary" size="sm"><Icon.Refresh className="h-3.5 w-3.5" /> Re-shuffle & edit teams</Button></Link></div>}</div>
    <div className="grid min-h-0 gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><section className="min-w-0"><Card className="overflow-hidden xl:sticky xl:top-5"><CardHeader><CardTitle><span className="inline-flex items-center gap-2"><Icon.FileText className="h-4 w-4 text-[var(--fg-muted)]" /> Project brief</span></CardTitle>{(assignment.sourceType === "pdf" || assignment.sourceType === "docx") && <a href={documentUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 text-xs font-medium text-[var(--accent)] hover:underline"><Icon.Download className="h-3.5 w-3.5" /> {assignment.sourceType === "docx" ? "Download DOCX" : "Open PDF"}</a>}</CardHeader><CardContent className={assignment.sourceType === "pdf" ? "p-0" : undefined}>{brief}</CardContent></Card></section>
      <aside className="flex min-w-0 flex-col gap-4"><Card><CardHeader><CardTitle>Project overview</CardTitle></CardHeader><CardContent className="grid gap-3 text-sm"><div className="flex items-center justify-between"><span className="text-[var(--fg-muted)]">Status</span><Badge tone={closed ? "neutral" : "success"}>{closed ? "Closed" : "Open"}</Badge></div><div className="flex items-center justify-between gap-4"><span className="text-[var(--fg-muted)]">Deadline</span><span className="text-right text-xs font-medium">{formatDateTime(assignment.closesAt)}</span></div><div className="flex items-center justify-between"><span className="text-[var(--fg-muted)]">Teams</span><span className="font-medium">{groups.length || assignment.groupCount || 0}</span></div><div className="flex items-center justify-between"><span className="text-[var(--fg-muted)]">Submissions</span><span className="font-medium">{submissionCount}</span></div><div className="flex items-center justify-between"><span className="text-[var(--fg-muted)]">Reviewed</span><span className="font-medium">{reviewedCount}/{submissionCount}</span></div>{assignment.track && <div className="flex items-center justify-between gap-4"><span className="text-[var(--fg-muted)]">Track</span><span className="text-right capitalize">{assignment.track.replace(/_/g, " ")}</span></div>}</CardContent></Card>
        {assignment.questions && <Card><CardHeader><CardTitle>Questions</CardTitle></CardHeader><CardContent><div className="mdcontent text-sm leading-relaxed" dangerouslySetInnerHTML={{ __html: marked(assignment.questions) as string }} /></CardContent></Card>}<Card><CardHeader><CardTitle><span className="inline-flex items-center gap-2"><Icon.Users className="h-4 w-4 text-[var(--fg-muted)]" /> Teams</span></CardTitle></CardHeader><CardContent className="flex flex-col gap-2">{groupsLoading ? <p className="py-3 text-sm text-[var(--fg-muted)]">Loading teams...</p> : groups.map((group) => <div key={group.id} className="rounded-lg border border-[var(--border)] bg-[var(--surface-muted)]/25 p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-medium">{group.name}</p><p className="mt-0.5 text-xs text-[var(--fg-muted)]">{group.memberIds.length} member{group.memberIds.length === 1 ? "" : "s"}</p></div><Button variant="ghost" size="sm" onClick={() => onCopyGroupLink(group.id)} title="Copy public team page"><Icon.Link className="h-3.5 w-3.5" /></Button></div><p className="mt-2 text-xs text-[var(--fg-muted)]">{copiedGroupId === group.id ? "Public team page copied." : group.shareToken ? "Public team page is ready." : "Create a public team page."}</p></div>)}{!groupsLoading && groups.length === 0 && <p className="py-3 text-sm text-[var(--fg-muted)]">No teams have been created yet.</p>}</CardContent></Card>
        {assignment.rubric && <Card><CardHeader><CardTitle>Rubric</CardTitle></CardHeader><CardContent><p className="whitespace-pre-wrap text-sm leading-relaxed text-[var(--fg-muted)]">{assignment.rubric}</p></CardContent></Card>}</aside></div>
    <AssignmentRoster assignmentId={assignment.id} />
  </div>;
}
